import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/providers/AuthProvider";
import { getServerSession, Session } from "next-auth";
import { authConfig } from "@/config/auth";
import { headers } from "next/headers";
import WrapperLayout from "@/components/layout/wrapper";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = (await getServerSession(authConfig)) as Session;
  const cookie = (await headers()).get("cookie") as string;
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} font-sans bg-[#DDE9F3] text-neutral-900 antialiased`}
      >
        <AuthProvider session={session} cookie={cookie}>
          <WrapperLayout>{children}</WrapperLayout>
        </AuthProvider>
      </body>
    </html>
  );
}
